// Conversation-Preserving Routes
// Generated by Conversation-Preserving APML Compiler
// Conservation of Conversation: Chat → App in 15 Minutes

const ConversationRoutes = [
  {
    path: '/patterns/general',
    name: 'GeneralPattern',
    component: () => import('../pages/patterns/PatternLibraryIndexPage.vue'),
    meta: {
      conversation: "I want to learn and apply proven methodologies to my challenges",
      educationalGoal: "Complete training system for design intelligence",
      userExperience: "Interactive learning with real-world application",
      requiredComponents: [],
      applicableThemes: [],
      intentPreservation: "complete"
    }
  },
  {
    path: '/patterns/general',
    name: 'GeneralPattern',
    component: () => import('../pages/patterns/PatternLibraryIndexPage.vue'),
    meta: {
      conversation: "I want to learn and apply proven methodologies to my challenges",
      educationalGoal: "Complete training system for design intelligence",
      userExperience: "Interactive learning with real-world application",
      requiredComponents: [],
      applicableThemes: [],
      intentPreservation: "complete"
    }
  },
  {
    path: '/patterns/research-methodology',
    name: 'ResearchMethodology',
    component: () => import('../pages/patterns/ResearchMethodologyPage.vue'),
    meta: {
      conversation: "What research methods will give me the insights I need?",
      educationalGoal: "Make research methodology accessible and systematic",
      userExperience: "Context-aware research planning and execution",
      requiredComponents: [],
      applicableThemes: [],
      intentPreservation: "complete"
    }
  },
  {
    path: '/patterns/general',
    name: 'GeneralPattern',
    component: () => import('../pages/patterns/PatternLibraryIndexPage.vue'),
    meta: {
      conversation: "I want to learn and apply proven methodologies to my challenges",
      educationalGoal: "Complete training system for design intelligence",
      userExperience: "Interactive learning with real-world application",
      requiredComponents: [],
      applicableThemes: [],
      intentPreservation: "complete"
    }
  },
  {
    path: '/patterns/design-intelligence',
    name: 'DesignIntelligence',
    component: () => import('../pages/patterns/DesignIntelligencePage.vue'),
    meta: {
      conversation: "How do I solve complex problems systematically using proven methodologies?",
      educationalGoal: "Teach human-centered problem solving through executable patterns",
      userExperience: "Guided methodology selection and intelligent execution",
      requiredComponents: [],
      applicableThemes: [],
      intentPreservation: "complete"
    }
  },
  {
    path: '/patterns/business-strategy',
    name: 'BusinessStrategy',
    component: () => import('../pages/patterns/BusinessStrategyPage.vue'),
    meta: {
      conversation: "How do I turn insights into successful business strategy?",
      educationalGoal: "Codify business strategy frameworks into reusable patterns",
      userExperience: "Strategic decision-making with intelligent recommendations",
      requiredComponents: [],
      applicableThemes: ["corporate_confidence"],
      intentPreservation: "complete"
    }
  }
]

export default ConversationRoutes
